name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create output directory
        run: mkdir -p output

      - name: Copy APK to output
        run: |
          cp app/build/outputs/apk/debug/*.apk output/ || true
          cp app/build/outputs/apk/release/*.apk output/ || true

      - name: Upload APKs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: apks
          path: output/