name: CI - commit message check + unit tests for create_change

on:
  push:
    branches:
      - create_change

jobs:
  commit-message:
    name: Commit message lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate commit messages
        shell: bash
        run: |
          set -euo pipefail

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_REF="${{ github.event.pull_request.base.ref }}"
            HEAD_REF="${{ github.event.pull_request.head.ref }}"
            git fetch origin "${BASE_REF}" "${HEAD_REF}"
            RANGE="origin/${BASE_REF}..origin/${HEAD_REF}"
          else
            if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
              RANGE="${{ github.sha }}"
            else
              RANGE="${{ github.event.before }}..${{ github.sha }}"
            fi
          fi

          COMMITS=$(git rev-list --no-merges $RANGE || true)

          if [ -z "$COMMITS" ]; then
            echo "No commits found to check."
            exit 0
          fi

          echo "Validating $(echo "$COMMITS" | wc -l) commits..."

          regex='^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert)(\([[:alnum:]._/-]+\))?: .+'
          failed=0
          for rev in $COMMITS; do
            msg=$(git log -1 --pretty=%B "$rev" | sed -n '1p' | tr -d '\r')
            echo "Checking $rev -> \"$msg\""
            if ! [[ "$msg" =~ $regex ]]; then
              echo ""
              echo "Commit $rev message does not match Conventional Commits pattern:"
              echo "  $msg"
              echo ""
              failed=1
            fi
          done

          if [ "$failed" -ne 0 ]; then
            echo "Commit message validation failed. Expected: <type>(optional-scope): <description>"
            exit 1
          fi

          echo "All commit messages passed the check."

  unit-tests:
    name: Run unit tests (Gradle)
    runs-on: ubuntu-latest
    needs: commit-message
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle*', '**/gradle/**') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew || true

      - name: Run Gradle unit tests
        run: ./gradlew test --no-daemon --console=plain