# Android check workflow for branch `create_change`
# Triggers on push and pull_request for the create_change branch.
# Runs checkout, sets up JDK 21 with Gradle cache and runs `./gradlew check`.
# Does NOT copy/upload artifacts.
name: CI Check

on:
  push:
    branches: [ "create_change" ]


jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle checks
        run: ./gradlew check --no-daemon --stacktrace

      - name: Upload test reports on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            app/build/reports/
            app-debug/build/reports/
          retention-days: 7